general:
  kafka-topic: transactions

server:
  port: 33400

spring:
  kafka:
    consumer:
      group-id: midas-core
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

incentive:
  api:
    base-url: http://localhost:8080
